server:
  port: 8002
spring:
  jpa:
    properties:
      hibernate:
        default_schema: task_schema
  output:
    ansi:
      enabled: always
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
task:
  language: en
  encoding: UTF-8
  security:
    allowed-origins:
      - ""
