spring:
  profiles:
    active: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  main:
    log-startup-info: false
  liquibase:
    change-log: classpath:/database/changelogs/changelog-master.xml
    default-schema: task_schema
server:
  port: 8099
---