spring:
  jpa:
    openInView: false
    show_sql: false
    generate-ddl: false
  main:
    log-startup-info: false
    banner-mode: off
  jackson:
    default-property-inclusion: non_null
server:
  port: 8100
task:
  language: en
  encoding: UTF-8
