spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:task_schema;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;IGNORECASE=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS TASK_SCHEMA
    username: sa
    password:
    initialization-mode: always
  liquibase:
    default-schema: task_schema
    drop-first: true
    change-log: classpath:/database/changelogs/changelog-master.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
