spring:
  liquibase:
    change-log: classpath:/database/changelogs/changelog-master.yml
    default-schema: task_schema
  jpa:
    openInView: false
    show_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.default-schema: task_schema
  main:
    log-startup-info: false
    banner-mode: off
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: always
server:
  port: 8099
task:
  language: en
  encoding: UTF-8

