spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:task_schema;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS TASK_SCHEMA
    username: sa
    password:
    initialization-mode: always
  liquibase:
    drop-first: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
