version: "3.8"

services:
  task-database:
    image: postgres:16.1
    container_name: task-database
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./taskDb:/var/lib/postgresql/data
    networks:
      task-network:
    healthcheck:
      test: pg_isready -q -U ${DB_USER} -d ${DB_DATABASE}
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 2G

  task-schema:
    image: azjarosz/task-schema:${APP_VERSION}
    container_name: task-schema
    build:
      context: ../database
      dockerfile: database-schema.Dockerfile
      args:
        - GITHUB_MAVEN_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ${ENV_FILE}
    networks:
      task-network:
    depends_on:
      task-database:
        condition: service_healthy

  task-sample-data:
    image: azjarosz/task-sample-data:${APP_VERSION}
    container_name: task-sample-data
    build:
      context: ../sample-data
      dockerfile: sample-data.Dockerfile
      args:
        - GITHUB_MAVEN_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ${ENV_FILE}
    networks:
      task-network:
    depends_on:
      task-schema:
        condition: service_completed_successfully

  task-backend:
    image: azjarosz/task-backend:${APP_VERSION}
    container_name: task-backend
    build:
      context: ../core
      dockerfile: core.Dockerfile
      args:
        - GITHUB_MAVEN_TOKEN=${GITHUB_TOKEN}
    env_file:
      - ${ENV_FILE}
    networks:
      task-network:
    ports:
      - 8100:${BACKEND_PORT}
    depends_on:
      task-sample-data:
        condition: service_completed_successfully

networks:
  task-network:


