spring:
  profiles:
    active: postgres
  # should be provided by properties of run template
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/taskdb
  #    username: postgres
  #    password: postgres123
  #    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.default_schema: task_schema
  main:
    log-startup-info: false
    banner-mode: off

  jackson:
    default-property-inclusion: non_null
server:
  port: 8099
task:
  language: en
  encoding: UTF-8
