spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    openInView: false
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        cache:
          use_query_cache: false
        generate_statistics: false
        default_schema: task_schema
        integration:
          envers:
            enabled: ${ENABLE_HISTORY}
  main:
    log-startup-info: false
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: always
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_BE_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    audience: ${AUTH0_AUDIENCE}

task:
  language: en
  encoding: UTF-8
  security:
    allowed-origins:
      - ${ALLOWED_ORIGIN}
