name: Workflow without publishing one job

# This should ignore branches, that are connected with publishing artifacts and should run only on working ones.
on:
  push:
    branches-ignore:
      - develop
      - 'release/**'
      - 'TA-**'

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'zulu'

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event."
      - run: echo "Runner ${{ runner.os }}"
      - run: echo "Branch ${{ github.ref }}"
      - name: echo "All git properties"
        run: echo "git is - ${{ toJson(github) }} "
      - uses: actions/checkout@v4
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
      - name: Displaying build number
        run: echo "Build number $BUILD_NUMBER started."
      - name: Set up JDK version ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION}}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run maven verify
        run: mvn verify
      - run: echo " This job's status is ${{ job.status }}."
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run maven verify
        run: mvn verify
      - run: echo " This job's status is ${{ job.status }}."
