name: Workflow without publishing

# This should ignore branches, that are connected with publishing artifacts and should run only on working ones.
on:
  push:
    branches-ignore:
      - develop
      - 'release/**'

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
      - name: displaying build number
        run: echo "Build number $BUILD_NUMBER started."
      - name: Set up JDK version ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run maven verify
        run: mvn verify
      - run: echo " This job's status is ${{ job.status }}."

  liquibase_test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK version ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run maven verify
        run: mvn verify
      - run: echo " This job's status is ${{ job.status }}."
